export type AudioFeature =
    | "MFCC0"
    | "MFCC1"
    | "MFCC2"
    | "MFCC3"
    | "MFCC4"
    | "MFCC5"
    | "MFCC6"
    | "MFCC7"
    | "MFCC8"
    | "MFCC9"
    | "MFCC10"
    | "MFCC11"
    | "MFCC12"
    | "chroma1"
    | "chroma2"
    | "chroma3"
    | "chroma4"
    | "chroma5"
    | "chroma6"
    | "chroma7"
    | "chroma8"
    | "chroma9"
    | "chroma10"
    | "chroma11"
    | "chroma12"
    | "spectralCentroid"
    | "spectralRolloff"
    | "spectralFlatness"
    | "spectralKurtosis"
    | "spectralSkewness"
    | "spectralSlope"
    | "spectralSpread"
    | "spectralCrest"
    | "spectralFlux"
    | "spectralRolloff"
    | "zcr"
    | "rms"
    | "loudness"
    | "perceptualSharpness"
    | "perceptualSpread"
    | "energy"
    | "amplitudeSpectrum"
    | "powerSpectrum"
    | "complexSpectrum"
    | "buffer"
    | "melBands"
    | "chroma"
    | "perceptualSpread"
    | "perceptualSharpness"
    | "spectralKurtosis"
    | "spectralSkewness"
    | "spectralSlope"
    | "spectralSpread"
    | "spectralCrest"
    | "spectralFlux"
    | "spectralRolloff"
    | "zcr"
    | "rms"
    | "loudness"
    | "perceptualSharpness"
    | "perceptualSpread"
    | "energy"
    | "amplitudeSpectrum"
    | "powerSpectrum"
    | "complexSpectrum"
    | "buffer"
    | "melBands"
    | "chroma"
    | "perceptualSpread"
    | "perceptualSharpness"
    | "spectralKurtosis"
    | "spectralSkewness"
    | "spectralSlope"
    | "spectralSpread"
    | "spectralCrest"
    | "spectralFlux"
    | "spectralRolloff"
    | "zcr"
    | "rms"
    | "loudness"
    | "perceptualSharpness"
    | "perceptualSpread";

export type MfccCoefficientType =
    | "MFCC0"
    | "MFCC1"
    | "MFCC2"
    | "MFCC3"
    | "MFCC4"
    | "MFCC5"
    | "MFCC6"
    | "MFCC7"
    | "MFCC8"
    | "MFCC9"
    | "MFCC10"
    | "MFCC11"
    | "MFCC12";

export type OscillatorDataSource = "osc1" | "osc2" | "osc3";

export type ModulationDataSource = AudioFeature | OscillatorDataSource | "none";

// we might need a global store to route the control data

export type TimbreCanvasModulationSource = {
    xPos: ModulationDataSource;
    yPos: ModulationDataSource;
    hue: ModulationDataSource;
    opacity: ModulationDataSource;
    scale: ModulationDataSource;
    globalScale: ModulationDataSource;
};
